<a href="https://colab.research.google.com/github/hoseinm444/FanapExercises/blob/main/FFCVS_Dec23_Python_Ex03_Hosein_Mohammadi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercises 03


Numpy, Pandas, OOP

##Exercise 01


Create an 3d numpy array with dimensions (4, 5, 3), and print the dimensions finally.

In [ ]:
import numpy as np
arr_3d = np.array(  [   [[1,2,3],[4,5,6] ,[7,8,9],[10,11,12],[13,14,15]] ,
                        [[1,2,3],[4,5,6] ,[7,8,9],[10,11,12],[13,14,15]] ,
                        [[1,2,3],[4,5,6] ,[7,8,9],[10,11,12],[13,14,15]] ,
                        [[1,2,3],[4,5,6] ,[7,8,9],[10,11,12],[13,14,15]]
                    ]   )
#first [] for definition
#second [] for row we have 5 rows
#third row for elements
arr_3d.shape

(4, 5, 3)

##Exercise 02


change the shape of created array in the exercise 01 to (20, 3) and check the current dimensions!

In [ ]:
arr_for_resh= np.reshape(arr_3d,(20,3))
arr_for_resh.shape

(20, 3)

##Exercise 03


index and print the number 50 from the arr.
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [ ]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
b = arr[1,0]
b

50

##Exercise 04


Change the element datatype of the arr to float!
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [ ]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]],dtype = 'f')
float_arr = arr.astype(float)
float_arr

array([[10., 20., 30., 40.],
       [50., 60., 70., 80.]])

##Exercise 05


join arr1 and arr2 into a single array!

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate((arr1, arr2))
arr3

array([1, 2, 3, 4, 5, 6])

##Exercise 06


Load the dataset (cancer.csv)!

In [ ]:
import pandas as pd
df = pd.read_csv('cancer.csv')
df

,State,Total.Rate,Total.Number,Total.Population,Rates.Age.< 18,Rates.Age.18-45,Rates.Age.45-64,Rates.Age.> 64,Rates.Age and Sex.< 18.Female,Rates.Age and Sex.< 18.Male,...,Types.Lung.Age and Sex.Male.45 - 64,Types.Lung.Age and Sex.Female.> 64,Types.Lung.Age and Sex.Male.> 64,Types.Lung.Race.White,Types.Lung.Race.White non-Hispanic,Types.Lung.Race.Black,Types.Lung.Race.Black non-Hispanic,Types.Lung.Race.Asian,Types.Lung.Race.Indigenous,Types.Lung.Race.Hispanic
0,Alabama,214.2,71529.0,33387205.0,2.0,18.5,244.7,1017.8,2.0,2.1,...,102.9,221.7,457.4,59.9,60.4,52.6,52.8,23.0,22.9,14.8
1,Alaska,128.1,6361.0,4966180.0,1.7,11.8,170.9,965.2,0.0,0.0,...,50.3,268.3,335.0,48.7,49.5,45.6,47.9,33.0,74.4,0.0
2,Arizona,165.6,74286.0,44845598.0,2.5,13.6,173.6,840.2,2.6,2.5,...,47.0,191.9,275.8,39.5,42.2,38.2,40.4,21.3,11.1,21.6
3,Arkansas,223.9,45627.0,20382448.0,2.3,17.6,250.1,1048.3,2.6,2.0,...,106.5,248.7,484.7,63.4,64.2,62.9,63.0,18.1,16.2,14.6
4,California,150.9,393980.0,261135696.0,2.6,13.7,163.7,902.4,2.4,2.8,...,36.8,192.5,269.0,37.2,42.6,46.5,48.6,25.8,18.4,18.3
5,Colorado,139.0,49035.0,35267734.0,1.9,11.7,149.6,849.4,1.9,1.9,...,34.0,183.0,242.6,34.1,35.0,40.4,41.5,22.8,22.3,25.6
6,Connecticut,190.5,47567.0,24975889.0,1.6,13.6,163.6,971.2,1.6,1.7,...,47.2,222.2,301.1,42.2,43.2,38.4,40.4,20.8,0.0,20.3
7,Delaware,210.2,13233.0,6295263.0,2.2,16.0,217.5,993.3,0.0,0.0,...,74.9,253.7,369.1,55.0,55.7,49.3,49.8,23.7,0.0,15.5
8,District of Columbia,182.1,7730.0,4245359.0,0.0,12.4,251.8,1028.6,0.0,0.0,...,71.3,193.0,303.2,27.3,27.6,53.6,54.2,0.0,0.0,18.8
9,Florida,219.2,289905.0,132277071.0,2.1,15.9,206.9,901.2,2.0,2.2,...,72.0,215.8,329.0,48.0,52.5,38.1,39.5,19.8,21.0,24.0
10,Georgia,159.4,108222.0,67890652.0,2.2,15.7,205.6,932.2,2.0,2.3,...,74.0,210.9,383.3,52.4,53.7,45.1,45.4,19.1,0.0,10.6
11,Hawaii,166.0,15812.0,9526083.0,2.5,14.9,171.1,787.8,2.2,2.8,...,44.0,153.0,269.3,36.0,37.2,39.6,43.0,32.6,0.0,35.2
12,Idaho,162.1,17756.0,10954295.0,1.9,13.5,168.8,912.2,2.1,1.8,...,42.4,204.1,278.2,39.2,39.9,0.0,0.0,0.0,28.1,19.8
13,Illinois,189.2,169730.0,89696961.0,2.3,14.6,198.6,1037.9,2.0,2.5,...,63.4,240.9,370.7,49.5,51.8,60.1,60.3,21.4,12.6,17.5
14,Indiana,202.7,91978.0,45372690.0,2.4,16.3,218.2,1059.7,2.3,2.5,...,83.6,252.7,434.1,57.6,58.3,64.3,64.6,18.2,0.0,14.6
15,Iowa,210.3,44835.0,21322082.0,2.1,14.7,195.9,1018.1,1.7,2.5,...,69.3,217.6,367.3,48.2,48.6,66.0,66.7,24.6,0.0,18.1
16,Kansas,188.9,37644.0,19928783.0,2.7,14.0,194.4,999.6,2.5,2.8,...,66.0,226.4,368.3,48.0,48.8,59.9,60.8,30.0,81.7,23.8
17,Kentucky,226.3,68675.0,30348057.0,2.2,18.4,256.3,1110.2,1.8,2.7,...,112.6,298.3,519.1,71.5,71.9,73.2,73.6,25.9,0.0,22.0
18,Louisiana,202.9,64194.0,31638386.0,2.3,17.8,246.4,1053.3,1.9,2.7,...,92.2,239.1,432.5,56.2,57.5,61.6,62.0,31.4,24.2,12.8
19,Maine,239.1,22240.0,9301182.0,2.4,15.2,204.7,1061.8,2.4,2.4,...,74.9,259.1,388.1,54.7,54.6,0.0,0.0,0.0,45.1,0.0
20,Maryland,179.3,72603.0,40483979.0,2.0,15.2,189.1,977.5,1.7,2.2,...,58.3,231.0,331.3,47.2,48.5,47.0,47.5,19.8,16.6,10.8
21,Massachusetts,197.8,90756.0,45892272.0,2.1,13.3,177.8,1028.6,2.0,2.2,...,53.3,243.8,340.0,47.9,48.8,34.1,38.1,25.5,15.8,18.5
22,Michigan,205.3,142458.0,69388573.0,2.3,16.4,209.3,1016.3,2.1,2.5,...,71.8,244.7,372.6,51.3,51.7,59.3,59.4,18.7,65.2,29.8
23,Minnesota,178.4,66328.0,37183729.0,2.1,12.9,167.8,983.7,2.0,2.3,...,47.6,212.0,305.6,41.7,42.0,40.3,40.7,21.7,83.8,16.0
24,Mississippi,211.4,43874.0,20756872.0,2.4,19.5,263.9,1049.1,2.2,2.5,...,106.6,223.7,496.4,61.8,62.3,60.1,60.4,33.9,0.0,12.6
25,Missouri,211.2,88348.0,41838390.0,2.3,16.3,221.0,1030.8,2.2,2.4,...,83.1,257.3,419.5,57.1,57.6,60.2,60.5,21.0,27.7,18.5
26,Montana,196.1,13593.0,6933023.0,2.4,11.8,175.4,939.1,0.0,2.5,...,46.9,233.3,299.3,42.6,42.2,0.0,0.0,0.0,59.8,25.6
27,Nebraska,187.5,23977.0,12785524.0,2.7,13.1,179.8,999.5,2.4,3.0,...,54.4,210.8,348.8,44.2,44.8,62.7,64.0,26.6,54.8,18.1
28,Nevada,167.9,31758.0,18912307.0,1.9,13.4,183.7,944.2,1.8,2.1,...,52.0,263.7,325.9,52.1,56.0,44.7,46.1,23.4,27.8,20.4
29,New Hampshire,197.9,18256.0,9223389.0,2.2,14.7,175.2,1009.2,2.9,0.0,...,53.6,246.0,336.8,48.5,48.7,32.6,0.0,0.0,0.0,0.0
30,New Jersey,189.9,116836.0,61521555.0,2.1,14.4,174.8,999.6,1.9,2.2,...,48.5,216.6,317.5,43.9,46.4,42.8,45.4,17.7,12.0,17.9
31,New Mexico,163.2,23425.0,14349762.0,2.2,13.9,167.3,845.0,2.0,2.5,...,35.0,171.5,250.3,35.1,39.3,42.9,47.2,20.2,8.9,26.3
32,New York,183.2,248572.0,135716524.0,2.4,14.3,182.4,942.9,2.2,2.6,...,53.7,208.3,309.1,44.7,46.7,35.6,39.2,23.3,13.8,21.0
33,North Carolina,188.7,125783.0,66669069.0,2.0,15.8,212.6,963.3,1.8,2.2,...,81.6,220.8,409.4,53.4,54.3,51.8,52.2,22.7,50.4,11.3
34,North Dakota,189.1,8990.0,4754903.0,2.1,10.0,165.4,981.7,0.0,0.0,...,45.6,185.6,342.6,39.8,39.7,0.0,0.0,0.0,87.5,0.0
35,Ohio,217.8,175847.0,80741243.0,2.0,16.9,220.2,1061.6,1.9,2.0,...,80.3,250.6,407.9,54.8,55.1,62.9,63.3,25.4,21.5,18.5
36,Oklahoma,209.4,54930.0,26229144.0,2.4,16.3,238.9,1040.5,1.9,2.9,...,88.7,256.6,436.7,59.4,60.5,59.7,60.1,32.1,57.3,19.8
37,Oregon,199.1,53430.0,26832116.0,2.4,13.4,191.3,1001.4,2.2,2.5,...,53.4,250.7,329.6,47.2,48.0,55.3,57.1,29.9,37.2,20.5
38,Pennsylvania,227.7,202230.0,88825682.0,2.2,15.7,204.1,1057.3,2.1,2.4,...,66.5,225.8,373.4,48.1,48.4,60.2,61.4,23.4,20.9,19.8
39,Rhode Island,211.2,15570.0,7371636.0,1.4,13.3,190.3,1052.1,0.0,0.0,...,64.2,247.9,379.8,51.7,53.0,33.7,39.5,25.5,0.0,15.0
40,South Carolina,202.6,65561.0,32366134.0,2.1,17.0,235.5,957.1,2.1,2.2,...,91.3,212.9,393.9,54.3,54.8,49.4,48.7,23.4,40.8,19.2
41,South Dakota,196.2,11212.0,5714307.0,2.3,12.4,175.7,1007.1,0.0,3.2,...,56.4,206.2,361.2,43.9,44.2,0.0,0.0,0.0,70.3,0.0
42,Tennessee,213.1,94678.0,44430836.0,2.4,17.7,245.2,1032.1,2.3,2.5,...,101.0,248.4,461.5,61.5,62.1,62.1,62.5,25.8,21.3,8.8
43,Texas,145.8,257000.0,176270421.0,2.5,14.7,186.6,904.8,2.3,2.7,...,54.3,200.0,331.9,42.9,50.1,54.1,54.9,22.2,9.0,20.8
44,Utah,98.5,19022.0,19321462.0,1.9,10.9,132.3,735.8,1.6,2.2,...,26.0,92.7,153.2,20.4,20.6,31.1,35.0,18.5,17.8,17.3
45,Vermont,211.6,9261.0,4377262.0,2.2,16.2,188.1,1002.8,0.0,0.0,...,59.7,243.6,337.0,49.7,49.8,0.0,0.0,0.0,0.0,0.0
46,Virginia,177.1,99278.0,56054333.0,2.2,14.5,189.3,971.0,1.9,2.5,...,63.4,226.2,359.8,48.7,49.5,52.6,52.7,23.7,17.0,15.3
47,Washington,175.9,82864.0,47114240.0,2.3,13.2,177.5,982.0,2.3,2.3,...,49.4,241.1,317.9,46.3,47.2,46.6,47.8,29.0,43.4,18.2
48,West Virginia,254.6,32950.0,12940212.0,2.5,20.3,254.0,1068.9,2.2,2.7,...,100.2,264.7,445.8,62.7,63.0,59.1,59.6,0.0,0.0,0.0
49,Wisconsin,197.5,78578.0,39788899.0,2.2,13.8,181.2,1028.1,2.1,2.2,...,55.0,223.1,339.9,44.6,45.1,70.6,71.7,20.6,79.0,16.1
50,Wyoming,167.9,6603.0,3931624.0,0.0,11.8,168.3,924.9,0.0,0.0,...,39.0,205.6,290.4,40.0,40.8,0.0,0.0,0.0,55.2,21.4

##Exercise 07


Print an overview of the dataset

In [ ]:
df.info()
#df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   State                                         51 non-null     object
 1   Total.Rate                                    51 non-null     float64
 2   Total.Number                                  51 non-null     float64
 3   Total.Population                              51 non-null     float64
 4   Rates.Age.< 18                                51 non-null     float64
 5   Rates.Age.18-45                               51 non-null     float64
 6   Rates.Age.45-64                               51 non-null     float64
 7   Rates.Age.> 64                                51 non-null     float64
 8   Rates.Age and Sex.< 18.Female                 51 non-null     float64
 9   Rates.Age and Sex.< 18.Male                   51 non-null     float64
 10  Rates.Age and Sex.18 - 45.Female              51 non-null     float64
 11  Rates.Age and Sex.18 - 45.Male                51 non-null     float64
 12  Rates.Age and Sex.45 - 64.Female              51 non-null     float64
 13  Rates.Age and Sex.45 - 64.Male                51 non-null     float64
 14  Rates.Age and Sex.> 64.Female                 51 non-null     float64
 15  Rates.Age and Sex.> 64.Male                   51 non-null     float64
 16  Rates.Race.White                              51 non-null     float64
 17  Rates.Race.White non-Hispanic                 51 non-null     float64
 18  Rates.Race.Black                              51 non-null     float64
 19  Rates.Race.Asian                              51 non-null     float64
 20  Rates.Race.Indigenous                         51 non-null     float64
 21  Rates.Race and Sex.Female.White               51 non-null     float64
 22  Rates.Race and Sex.Female.White non-Hispanic  51 non-null     float64
 23  Rates.Race and Sex.Female.Black               51 non-null     float64
 24  Rates.Race and Sex.Female.Black non-Hispanic  51 non-null     float64
 25  Rates.Race and Sex.Female.Asian               51 non-null     float64
 26  Rates.Race and Sex.Female.Indigenous          51 non-null     float64
 27  Rates.Race and Sex.Male.White                 51 non-null     float64
 28  Rates.Race and Sex.Male.White non-Hispanic    51 non-null     float64
 29  Rates.Race and Sex.Male.Black                 51 non-null     float64
 30  Rates.Race and Sex.Male.Black non-Hispanic    51 non-null     float64
 31  Rates.Race and Sex.Male.Asian                 51 non-null     float64
 32  Rates.Race and Sex.Male.Indigenous            51 non-null     float64
 33  Rates.Race.Hispanic                           51 non-null     float64
 34  Rates.Race and Sex.Female.Hispanic            51 non-null     float64
 35  Rates.Race and Sex.Male.Hispanic              51 non-null     float64
 36  Types.Breast.Total                            51 non-null     float64
 37  Types.Breast.Age.18 - 44                      51 non-null     float64
 38  Types.Breast.Age.45 - 64                      51 non-null     float64
 39  Types.Breast.Age.> 64                         51 non-null     float64
 40  Types.Breast.Race.White                       51 non-null     float64
 41  Types.Breast.Race.White non-Hispanic          51 non-null     float64
 42  Types.Breast.Race.Black                       51 non-null     float64
 43  Types.Breast.Race.Black non-Hispanic          51 non-null     float64
 44  Types.Breast.Race.Asian                       51 non-null     float64
 45  Types.Breast.Race.Indigenous                  51 non-null     float64
 46  Types.Breast.Race.Hispanic                    51 non-null     float64
 47  Types.Colorectal.Total                        51 non-null     float64
 48  Types.Colorectal.Age and Sex.Female.18 - 44   51 non-null     float64
 49  Types.Colorectal.Age and Sex.Male.18 - 44     51 non-null     float64
 50  Types.Colorectal.Age and Sex.Female.45 - 64   51 non-null     float64
 51  Types.Colorectal.Age and Sex.Male.45 - 64     51 non-null     float64
 52  Types.Colorectal.Age and Sex.Female.> 64      51 non-null     float64
 53  Types.Colorectal.Age and Sex.Male.> 64        51 non-null     float64
 54  Types.Colorectal.Race.White                   51 non-null     float64
 55  Types.Colorectal.Race.White non-Hispanic      51 non-null     float64
 56  Types.Colorectal.Race.Black                   51 non-null     float64
 57  Types.Colorectal.Race.Black non-Hispanic      51 non-null     float64
 58  Types.Colorectal.Race.Asian                   51 non-null     float64
 59  Types.Colorectal.Race.Indigenous              51 non-null     float64
 60  Types.Colorectal.Race.Hispanic                51 non-null     float64
 61  Types.Lung.Total                              51 non-null     float64
 62  Types.Lung.Age and Sex.Female.18 - 44         51 non-null     float64
 63  Types.Lung.Age and Sex.Male.18 - 44           51 non-null     float64
 64  Types.Lung.Age and Sex.Female.45 - 64         51 non-null     float64
 65  Types.Lung.Age and Sex.Male.45 - 64           51 non-null     float64
 66  Types.Lung.Age and Sex.Female.> 64            51 non-null     float64
 67  Types.Lung.Age and Sex.Male.> 64              51 non-null     float64
 68  Types.Lung.Race.White                         51 non-null     float64
 69  Types.Lung.Race.White non-Hispanic            51 non-null     float64
 70  Types.Lung.Race.Black                         51 non-null     float64
 71  Types.Lung.Race.Black non-Hispanic            51 non-null     float64
 72  Types.Lung.Race.Asian                         51 non-null     float64
 73  Types.Lung.Race.Indigenous                    51 non-null     float64
 74  Types.Lung.Race.Hispanic                      51 non-null     float64
dtypes: float64(74), object(1)
memory usage: 30.0+ KB

##Exercise 08


Print 13 last samples of the dataset

In [ ]:
df.tail(13)

,State,Total.Rate,Total.Number,Total.Population,Rates.Age.< 18,Rates.Age.18-45,Rates.Age.45-64,Rates.Age.> 64,Rates.Age and Sex.< 18.Female,Rates.Age and Sex.< 18.Male,...,Types.Lung.Age and Sex.Male.45 - 64,Types.Lung.Age and Sex.Female.> 64,Types.Lung.Age and Sex.Male.> 64,Types.Lung.Race.White,Types.Lung.Race.White non-Hispanic,Types.Lung.Race.Black,Types.Lung.Race.Black non-Hispanic,Types.Lung.Race.Asian,Types.Lung.Race.Indigenous,Types.Lung.Race.Hispanic
38,Pennsylvania,227.7,202230.0,88825682.0,2.2,15.7,204.1,1057.3,2.1,2.4,...,66.5,225.8,373.4,48.1,48.4,60.2,61.4,23.4,20.9,19.8
39,Rhode Island,211.2,15570.0,7371636.0,1.4,13.3,190.3,1052.1,0.0,0.0,...,64.2,247.9,379.8,51.7,53.0,33.7,39.5,25.5,0.0,15.0
40,South Carolina,202.6,65561.0,32366134.0,2.1,17.0,235.5,957.1,2.1,2.2,...,91.3,212.9,393.9,54.3,54.8,49.4,48.7,23.4,40.8,19.2
41,South Dakota,196.2,11212.0,5714307.0,2.3,12.4,175.7,1007.1,0.0,3.2,...,56.4,206.2,361.2,43.9,44.2,0.0,0.0,0.0,70.3,0.0
42,Tennessee,213.1,94678.0,44430836.0,2.4,17.7,245.2,1032.1,2.3,2.5,...,101.0,248.4,461.5,61.5,62.1,62.1,62.5,25.8,21.3,8.8
43,Texas,145.8,257000.0,176270421.0,2.5,14.7,186.6,904.8,2.3,2.7,...,54.3,200.0,331.9,42.9,50.1,54.1,54.9,22.2,9.0,20.8
44,Utah,98.5,19022.0,19321462.0,1.9,10.9,132.3,735.8,1.6,2.2,...,26.0,92.7,153.2,20.4,20.6,31.1,35.0,18.5,17.8,17.3
45,Vermont,211.6,9261.0,4377262.0,2.2,16.2,188.1,1002.8,0.0,0.0,...,59.7,243.6,337.0,49.7,49.8,0.0,0.0,0.0,0.0,0.0
46,Virginia,177.1,99278.0,56054333.0,2.2,14.5,189.3,971.0,1.9,2.5,...,63.4,226.2,359.8,48.7,49.5,52.6,52.7,23.7,17.0,15.3
47,Washington,175.9,82864.0,47114240.0,2.3,13.2,177.5,982.0,2.3,2.3,...,49.4,241.1,317.9,46.3,47.2,46.6,47.8,29.0,43.4,18.2
48,West Virginia,254.6,32950.0,12940212.0,2.5,20.3,254.0,1068.9,2.2,2.7,...,100.2,264.7,445.8,62.7,63.0,59.1,59.6,0.0,0.0,0.0
49,Wisconsin,197.5,78578.0,39788899.0,2.2,13.8,181.2,1028.1,2.1,2.2,...,55.0,223.1,339.9,44.6,45.1,70.6,71.7,20.6,79.0,16.1
50,Wyoming,167.9,6603.0,3931624.0,0.0,11.8,168.3,924.9,0.0,0.0,...,39.0,205.6,290.4,40.0,40.8,0.0,0.0,0.0,55.2,21.4

##Exercise 09


Print states with total rate of less than 200

In [ ]:
states_less_200 = df[df['Total.Rate'] < 200]
states_less_200[['Total.Rate','State']]

    Total.Rate                 State
1        128.1                Alaska
2        165.6               Arizona
4        150.9            California
5        139.0              Colorado
6        190.5           Connecticut
8        182.1  District of Columbia
10       159.4               Georgia
11       166.0                Hawaii
12       162.1                 Idaho
13       189.2              Illinois
16       188.9                Kansas
20       179.3              Maryland
21       197.8         Massachusetts
23       178.4             Minnesota
26       196.1               Montana
27       187.5              Nebraska
28       167.9                Nevada
29       197.9         New Hampshire
30       189.9            New Jersey
31       163.2            New Mexico
32       183.2              New York
33       188.7        North Carolina
34       189.1          North Dakota
37       199.1                Oregon
41       196.2          South Dakota
43       145.8                 Texas
44        98.5                  Utah
46       177.1              Virginia
47       175.9            Washington
49       197.5             Wisconsin
50       167.9               Wyoming

##Exercise 10


Print number of states with total rate of less than 200

In [ ]:
states_less_200 = df[df['Total.Rate'] < 200]
states_less_200.count()

State                                 31
Total.Rate                            31
Total.Number                          31
Total.Population                      31
Rates.Age.< 18                        31
                                      ..
Types.Lung.Race.Black                 31
Types.Lung.Race.Black non-Hispanic    31
Types.Lung.Race.Asian                 31
Types.Lung.Race.Indigenous            31
Types.Lung.Race.Hispanic              31
Length: 75, dtype: int64

##Exercise 11


Print rows between 35 and 112 , and columns between 14 to 28 (use iloc)

In [ ]:
df_slicing = df.iloc[35:112,14:28]
df_slicing

,Rates.Age and Sex.> 64.Female,Rates.Age and Sex.> 64.Male,Rates.Race.White,Rates.Race.White non-Hispanic,Rates.Race.Black,Rates.Race.Asian,Rates.Race.Indigenous,Rates.Race and Sex.Female.White,Rates.Race and Sex.Female.White non-Hispanic,Rates.Race and Sex.Female.Black,Rates.Race and Sex.Female.Black non-Hispanic,Rates.Race and Sex.Female.Asian,Rates.Race and Sex.Female.Indigenous,Rates.Race and Sex.Male.White
35,895.1,1288.3,185.3,186.0,218.0,98.7,55.5,157.9,158.6,181.6,182.7,90.5,41.6,224.6
36,855.6,1279.4,190.2,192.6,222.1,122.1,194.2,159.0,160.8,181.4,182.5,127.1,162.3,232.7
37,866.0,1169.2,173.7,175.5,200.8,118.0,138.7,151.0,152.6,161.7,168.8,101.8,125.5,204.8
38,898.6,1276.5,177.7,178.2,222.4,96.5,56.7,151.7,152.3,189.6,192.9,85.6,43.8,215.5
39,884.4,1291.3,176.7,179.0,128.6,113.2,142.5,149.7,151.9,108.4,127.6,78.5,104.8,218.1
40,775.1,1195.1,175.1,176.1,211.2,88.1,102.2,144.0,144.5,165.0,163.3,84.8,80.2,218.2
41,860.7,1195.0,163.3,163.8,77.4,149.0,226.5,139.7,140.0,0.0,0.0,130.3,200.5,195.9
42,834.4,1294.7,189.4,190.9,231.6,93.5,62.0,153.7,154.9,185.2,186.3,88.6,59.1,239.3
43,750.2,1104.0,162.5,172.6,208.6,94.4,36.2,136.2,145.4,171.3,174.1,83.2,30.4,198.5
44,611.6,884.9,128.9,129.7,132.0,105.3,114.5,109.9,110.5,116.2,130.6,89.4,112.5,154.1
45,872.8,1165.8,175.0,175.0,130.3,109.2,0.0,151.4,151.3,0.0,0.0,112.1,0.0,207.8
46,819.2,1170.7,168.9,170.7,208.0,98.8,68.6,144.5,145.9,169.6,169.5,84.5,49.7,203.5
47,852.4,1142.0,171.3,173.5,189.0,120.1,167.8,149.4,151.3,153.7,157.1,103.4,147.4,201.4
48,889.6,1299.9,198.6,199.4,216.3,67.1,75.1,167.1,167.9,177.0,178.2,55.1,0.0,241.9
49,869.5,1233.6,169.9,170.9,235.1,107.9,214.0,145.1,146.1,195.5,198.5,93.5,193.7,205.4
50,803.4,1064.5,161.5,163.2,86.0,87.4,177.4,142.4,144.3,0.0,0.0,0.0,129.8,187.4

##Exercise 12


print unique values of the Rates.Age.< 18 column!

In [ ]:
uniqe_age_less_18 = df['Rates.Age.< 18'].unique
uniqe_age_less_18

<bound method Series.unique of 0     2.0
1     1.7
2     2.5
3     2.3
4     2.6
5     1.9
6     1.6
7     2.2
8     0.0
9     2.1
10    2.2
11    2.5
12    1.9
13    2.3
14    2.4
15    2.1
16    2.7
17    2.2
18    2.3
19    2.4
20    2.0
21    2.1
22    2.3
23    2.1
24    2.4
25    2.3
26    2.4
27    2.7
28    1.9
29    2.2
30    2.1
31    2.2
32    2.4
33    2.0
34    2.1
35    2.0
36    2.4
37    2.4
38    2.2
39    1.4
40    2.1
41    2.3
42    2.4
43    2.5
44    1.9
45    2.2
46    2.2
47    2.3
48    2.5
49    2.2
50    0.0
Name: Rates.Age.< 18, dtype: float64>

##Exercise 13


print mean of the Rates.Age.< 18

In [ ]:
mean_for_age_less_18 = df['Rates.Age.< 18'].mean()
mean_for_age_less_18_groupby = df.groupby('Rates.Age.< 18').mean()
mean_for_age_less_18
#mean_for_age_less_18_groupby

<ipython-input-81-3f03a45bcc3a>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  mean_for_age_less_18_groupby = df.groupby('Rates.Age.< 18').mean()

2.119607843137255

##Exercise 14

Find max of Total.Population and subtract all values of Total.Population column from the maximum value using lambda function

In [ ]:
max_of_population = df['Total.Population'].max()
population = df['Total.Population']
#res =(lambda i, j: i - j, max_of_population, population)
res = np.subtract(max_of_population,population)
res

0     227748491.0
1     256169516.0
2     216290098.0
3     240753248.0
4             0.0
5     225867962.0
6     236159807.0
7     254840433.0
8     256890337.0
9     128858625.0
10    193245044.0
11    251609613.0
12    250181401.0
13    171438735.0
14    215763006.0
15    239813614.0
16    241206913.0
17    230787639.0
18    229497310.0
19    251834514.0
20    220651717.0
21    215243424.0
22    191747123.0
23    223951967.0
24    240378824.0
25    219297306.0
26    254202673.0
27    248350172.0
28    242223389.0
29    251912307.0
30    199614141.0
31    246785934.0
32    125419172.0
33    194466627.0
34    256380793.0
35    180394453.0
36    234906552.0
37    234303580.0
38    172310014.0
39    253764060.0
40    228769562.0
41    255421389.0
42    216704860.0
43     84865275.0
44    241814234.0
45    256758434.0
46    205081363.0
47    214021456.0
48    248195484.0
49    221346797.0
50    257204072.0
Name: Total.Population, dtype: float64

##Exercise 15


Implement following architecture using OOP!

use __str__ to print output same as: Breed of the dog is {Breed}, It is {Size} and {Color} , the dog is {Age} years old

In [7]:
class Dog:
    # attribute and constructor
    def __init__(self, Name,Breed,Size,Age,Color):
        self.Dog_name = Name
        self.Dog_breed = Breed
        self.Dog_size = Size
        self.Dog_age = Age
        self.Dog_color = Color
    def Eat():
       print("It is eating.")
    def Sleep():
       print("It is sleeping.")
    def Sit():
       print("It is siting.")
    def Run():
       print("It is running.")
    def __str__(self):
       return f"Breed of the dog({self.Dog_name}) is {self.Dog_breed}, It is {self.Dog_size} and {self.Dog_age} , the dog is {self.Dog_color} years old."

# Object instantiation
Bella = Dog("Bella","Beaglier","Small",2,"red")
print(f'{Bella}')

Max = Dog("Max","Foxhound","big",3,"white")
print(f'{Max}')

Cooper = Dog("Bella","Beagle","Medium",2,"Brown")
print(f'{Cooper}')

Breed of the dog(Bella) is Beaglier, It is Small and 2 , the dog is red years old.
Breed of the dog(Max) is Foxhound, It is big and 3 , the dog is white years old.
Breed of the dog(Bella) is Beagle, It is Medium and 2 , the dog is Brown years old.